import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./components/navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Drone web-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${
          geistMono.variable
        } antialiased 
        bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100`} // <-- ปรับสีพื้นหลังและตัวอักษรหลัก
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}